### ISSUE TITLE
Missing postgres devel files

### ISSUE THREAD

**Issue by robinandeer** [arteria-project/arteria-provisioning#30]
I got this error during the mistral install: `Error: pg_config executable not found.`

So I added: `libpq-dev` under `mistral/tasks/install_deps.yml` and it seems to do the trick :smile:

**Comment by johandahlberg** [comment]
Have you got the latest version checked-out from `master`? I'm asking since when I'm looking here (and at my local machine) it looks like `libpq-dev` is already in there:
https://github.com/arteria-project/arteria-provisioning/blob/master/ansible-st2/roles/mistral/tasks/install_deps.yml

**Comment by johandahlberg** [comment]
And looking at the history it seems I added it 7days ago.

**Comment by robinandeer** [comment]
Sorry, I wasn't up-to-date
