### ISSUE TITLE
Memory requirements for testing environment

### ISSUE THREAD

**Issue by guillermo-carrasco** [arteria-project/arteria-provisioning#35]
Hej!

Trying to set up the testing environment following the readme in this repo, my laptop hanged. I ran out of memory (8GB). Looking at [the Vagrant file](https://github.com/arteria-project/arteria-provisioning/blob/master/Vagrantfile) I can understand why; there are heavy memory requirements for `testarteria1`.

Question: Is this necessary for the stack to work, or can it be lowered?

Thanks!

**Comment by johanherman** [comment]
This is for the bcl2fastq service. I.e. 8 GB is a bit on the low end even. :) But you can go ahead and lower the memory requirement if you just want be able to install it.

**Comment by guillermo-carrasco** [comment]
Ok I see, thanks! Will lower it to get it running locally :)

**Comment by guillermo-carrasco** [comment]
By the way, I would add a small note in the README about this, but up to you guys :)

**Comment by johandahlberg** [comment]
https://github.com/arteria-project/arteria-provisioning/pull/36 :p

**Comment by guillermo-carrasco** [comment]
oh wow, that's efficiency :sweat_smile: 

Thanks!
